[package]
name = "clasp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
digest = "0.10.7"
lazy_static = "1.5.0"
rand = "0.9.0"
rpassword = "7.3.1"
scanpw = "1.0.0"
serde = { version = "1.0.218", features = ["derive"] }
sha2 = "0.10.8"
